### ISSUE TITLE
userChrome.css for Tab text shadow blur

### ISSUE THREAD

**Issue by lowy** [lassekongo83/zuki-themes#100]
just like this:
![_2016-11-26_15-11-30](https://cloud.githubusercontent.com/assets/6565177/20638755/ef09bf0c-b3ea-11e6-9459-54254c470acc.png)

**Comment by lassekongo83** [comment]
Can't reproduce. Version of Firefox? Did you replace the default userChrome.css file instead of applying it in the Stylish extension?

**Comment by lowy** [comment]
yes Stylish extension ok thanks

**Comment by lowy** [comment]
yes Stylish extension ok thanks

**Comment by lowy** [comment]
yes Stylish extension ok thanks

**Comment by lowy** [comment]
yes Stylish extension ok thanks
