### ISSUE TITLE
Empathy Accounts → Invisible elements

### ISSUE THREAD

**Issue by timur-davletshin** [lassekongo83/zuki-themes#107]
Empathy window header turns black in Ubuntu 16.04 (Gnome Shell, Nvidia proprietary driver) and dialog box content is invisible. Problem exist both in Zukitwo and Zukitre. Stock themes in Ubuntu 16.04 are OK.
![untitled](https://cloud.githubusercontent.com/assets/23050090/24579203/40e4b356-16f9-11e7-9301-ca90c85b7e50.png)

**Comment by lassekongo83** [comment]
Are you using the right version? https://github.com/lassekongo83/zuki-themes/archive/3.18.zip

**Comment by timur-davletshin** [comment]
Yep, latest one.

**Comment by lassekongo83** [comment]
Fixed in the latest commit. (Though the switch shows on/off text which it shouldn't.)
