### ISSUE TITLE
Gnome 3.24

### ISSUE THREAD

**Issue by dirosis** [lassekongo83/zuki-themes#110]
Is there any chance for an update?

**Comment by lassekongo83** [comment]
Have you noticed any errors or bugs in 3.24? If I'm not mistaken the current theme from the master branch should work just fine.

**Comment by dirosis** [comment]
Generally it does except for Thunderbird and gimp which look rather ugly.
![gnome-shell-screenshot-4wcfyy](https://cloud.githubusercontent.com/assets/24278145/25000961/f2b3d296-204b-11e7-86b8-d45bf2b5c774.png)

**Comment by lassekongo83** [comment]
Those applications use GTK-2. Make sure the murrine gtk engine and the pixbuf gtk engine is installed. See: https://github.com/lassekongo83/zuki-themes#requirements

**Comment by dirosis** [comment]
Unfortunately it doesn't seem to work. Nevertheless I installed the gtk-chthemes which does not let me change to Zukitre for gtk2 apps but at least it has adwaita so it makes them look less ugly. Maybe it is an opensuse problem as in ubuntu which I used to use everything worked just fine.
