### ISSUE TITLE
Eclipse toolbar looks weird

### ISSUE THREAD

**Issue by imran27** [lassekongo83/zuki-themes#111]
![screenshot_2017-04-13-15 56 24](https://cloud.githubusercontent.com/assets/6375554/25001186/eaf60a04-2061-11e7-9a0b-ab3cc237ebff.png)

Arch Linux XFCE4. All eclipse based IDE look similarly weird.

**Comment by lassekongo83** [comment]
Let me know if the fix works.

**Comment by imranmunshi** [comment]
Fantastic @lassekongo83 
It works!
