### ISSUE TITLE
Use sassc instead of Ruby/sass

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#116]
Adwaita has switched[0] to using sassc instead of Ruby and its sass related libraries for parsing and creating the CSS files. Would you consider switching to it as well?

The advantage would be only having to install one program (sassc) instead of Ruby and dealing with the Gem installation.

[0] https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita/parse-sass.sh

**Comment by lassekongo83** [comment]
I'll eventually look into it.
