### ISSUE TITLE
Nautilus → Loading...

### ISSUE THREAD

**Issue by timur-davletshin** [lassekongo83/zuki-themes#121]
There is small "Loading..." message in Nautilus when opening big directories (bottom right corner). Background (and border) of that message is white while mask of that message is clearly visible when folder icon is in background. Any other color will look better — hard to notice message which can be useful especially if working with slow media like network shares. Yellow notification color will look fine IMHO.

**Comment by lassekongo83** [comment]
Yellow is not a color used in the theme. But I added some borders too it and changed the color to the standard bg-color.
