### ISSUE TITLE
TOR Browser tabs

### ISSUE THREAD

**Issue by timur-davletshin** [lassekongo83/zuki-themes#123]
![untitled](https://user-images.githubusercontent.com/23050090/28770252-260ac9d8-75e7-11e7-8833-1f59459d78b3.png)

is it possible to fix this tab issue? It is much less pronounced in Adwaita.

Thanks in advance.

**Comment by lassekongo83** [comment]
Try replacing the userChrome.css with [this one](https://github.com/lassekongo83/zuki-themes/blob/3.20/Zukitre-firefox-theme/chrome/userChrome.css). (Make a backup of the old one first.)

**Comment by timur-davletshin** [comment]
Not entirely what I expected, but it works for me. Thank you again.

**Comment by timur-davletshin** [comment]
Just noticed, it is no longer in master branch. Why?

**Comment by lassekongo83** [comment]
Firefox is changing quite a lot right now and the old way of making themes will no longer work, so I dropped it.
