### ISSUE TITLE
(filezilla:33214): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' fa IA__gtk_widget_set_size_request

### ISSUE THREAD

**Issue by heelsleeh** [lassekongo83/zuki-themes#124]
first: thanks for the great work, this theme is pretty awesome.
ENV:
gnome-shell 3.20

theme:
Zukitre

ERRORS ( gnome-3.20 and gnome-3.22 both have this issue)

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 44 and height -64

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 31

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 31

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 44 and height -64

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 31

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 31

(filezilla:41820): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 31

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -27

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

(filezilla:41820): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 1 and height -38

**Comment by lassekongo83** [comment]
3.20 is no longer supported. However, unable to reproduce on Debian Stretch with GNOME 3.22. Both with the master release of the theme and the last 3.22 release.

**Comment by heelsleeh** [comment]
thanks for reply
i think that might be  the i3 wm problem.
