### ISSUE TITLE
how to add a border?

### ISSUE THREAD

**Issue by heelsleeh** [lassekongo83/zuki-themes#130]
zukitre 3.22
issue
when some applications such as xterm stack together, it's can't see clearly. i think add a border to frame will be better, but i can't . could you tell me how ?
![xterm](https://user-images.githubusercontent.com/24011272/38400264-e653dce4-3981-11e8-96e9-9a228db34a2c.jpg)

**Comment by lassekongo83** [comment]
That's not Zukitre. You'll have to edit whatever window manager theme you're using.
