### ISSUE TITLE
how to add a border?

### ISSUE THREAD

**Issue by heelsleeh** [lassekongo83/zuki-themes#132]
zukitre
gnome-shell 3.26
issue
when some applications such as xterm stack together, it's can't see clearly. i think add a border to frame will be better, but i can't . could you help me?
![screenshot from 2018-05-12 22-44-15](https://user-images.githubusercontent.com/24011272/39958507-98aecb30-5636-11e8-9852-ffbb694215be.png)

**Comment by lassekongo83** [comment]
1. Install `sassc`
2. Open `_common.scss` and search for `decoration {`
3. Change `border-width: 0px;` to `1px` or more. Add `border-color: $bg_color;` below if necessary.</br>Do the same below with the `.ssd` class where you change `border: none` to `border-width: 1px;` or more.

4. Save and run the `parse-sass.sh` file and then reload the theme.

**Comment by heelsleeh** [comment]
thanks

**Comment by heelsleeh** [comment]
@lassekongo83, i fllowed your solution step by step, it seems not working.

**Comment by lassekongo83** [comment]
Actually, search for `0 0 0 1px $_wm_border;` and change that to `0 0 0 1px $bg_color;` instead.
