### ISSUE TITLE
Reverting Nemo changes

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#133]
I've just seen that a few fixes for Nemo have been removed in https://github.com/lassekongo83/zuki-themes/commit/bddf7c150dfdb060bf07081852d11d585f4a9383. Is there a reason for that and will they be brought back? The white sidebar is something that can be lived with. However the awkward file-renaming background is awkward, as mentioned in #73.

**Comment by lassekongo83** [comment]
One of the changes there caused some unnecessary bloat with the sidebar CSS. But the renaming background had nothing to do with it, so that is back.

**Comment by dglava** [comment]
Thanks.

One more question: I want to restore the other changes as well. I am getting this white text now when nothing in the sidebar is selected (picture below). What am I missing? I added back all of the Nemo specific things that were removed from _other.scss.

https://s8.postimg.cc/6npz6bz8l/2018-06-24-23_10_25.png

**Comment by lassekongo83** [comment]
Did you regenerate the CSS files? Install `sassc` and run `parse-sass.sh`.

**Comment by dglava** [comment]
Sorry, my bad. I didn't include all of the removed lines. It looks good now. Thanks.
