### ISSUE TITLE
Weird shadow next to app name in Gnome-Shell panel

### ISSUE THREAD

**Issue by pedrofleck** [lassekongo83/zuki-themes#134]
There's a shadow where the icon was supposed to be on default theme since Gnome 3.26, as shown here:
https://i.imgur.com/mm6mlGo.png
It's present in every theme without application icon showing, but I think the Arc theme fixed it:
https://github.com/horst3180/arc-theme/issues/824
Thanks in advance!

**Comment by lassekongo83** [comment]
That was fixed a while ago: https://github.com/lassekongo83/zuki-themes/commit/f263edca9df97d40eae7ee3957d9c557dbe2c49a
