### ISSUE TITLE
dark theme support 

### ISSUE THREAD

**Issue by elswerky** [lassekongo83/zuki-themes#135]
hello 
please can you provide dark theme of zuki theme ??? 

and more support of deepin desktop 
because what i get here on deepin desktop is the white theme (silver theme ) and no dark theme 

thx in advance

**Comment by lassekongo83** [comment]
There's a dark gtk3 theme that can be activated in gnome-tweaks. I have no plans on making a dark gtk2 version or providing a separate package.

**Comment by elswerky** [comment]
gnome tweaks not working on deepin desktop 

in deepin desktop i choose theme from control center

**Comment by lassekongo83** [comment]
That requires a metacity theme which I no longer support. The one already in the theme is no longer being maintained and may be removed at some point.

If gnome-tweaks doesn't work, rename `gtk-dark.css` to `gtk.css`.

**Comment by elswerky** [comment]
ok ,, thanks 

gnome tweak tool doesn't work only in deepin desktop because deepin desktop uses other tools in its setttings to choose themes ,,icons and fonts 

thank you

**Comment by elswerky** [comment]
thanks 
after i changed gtk.css to gtk.css.bak 
and changed  gtk-dark.css to gtk.css and now  i have the dark theme 

i noticed that there are 3 folders one called zukihow and this one conatina metacity folder so it appears in theme options in deepin control centre 

but the other foder called zukitre doesn't contain metacity folder ( so it doesn't appear in deepin desktop ) 

thank you for telling me how to enable it 
and if you had spare time please give a look at it and let both the dark and silver theme to appear in deepin control centre ,,,
not just the silver or having to change name to enable dark ,,,, you may have a look at the commits of the link i posted here about flat remix theme for rapid enabling of complete support of dark theme on deepin desktop without changing what you said because not every one know this step 
![deepinscreenshot_select-area_20180906125313](https://user-images.githubusercontent.com/26687459/45153325-d3893300-b1d3-11e8-92c5-70a0e9c020cd.png)

now i have dark theme enabled
