### ISSUE TITLE
Maximise button refinement in Zukitre

### ISSUE THREAD

**Issue by subhammridha** [lassekongo83/zuki-themes#136]
Hi,

I have been using plano-theme in all my computers for quite some time and therefore wanted to have a bit different theme for my laptop. Thus I was trying your Zukitre theme which, in my opinion, is also a great theme.

As with a recent modification in the plano-theme (https://github.com/lassekongo83/plano-theme/issues/18), it would be nice if you kindly incorporate the same in Zukitre as well so that the maximise/restore buttons have different symbols.

**Comment by subhammridha** [comment]
Thanks a lot!

**Comment by subhammridha** [comment]
One minute disturbance:

I can't press the close button from the extreme top right corner of a maximised window. Earlier, I remember, I could do that. But I am not sure now. Anyway this concept works with your other themes which is the primary reason (among other aesthetic refinements with your themes) I like to use your themes.

Thus my request is: Can this be implemented (again)?

Thanks in advance.

**Comment by lassekongo83** [comment]
I would have to remove the rounded corner for that and just make the window square, not sure that's exactly what I want to do.

**Comment by subhammridha** [comment]
I see. Let it be like this then.

Thanks again.
