### ISSUE TITLE
reduce height of titlebar?

### ISSUE THREAD

**Issue by eduarddrenth** [lassekongo83/zuki-themes#138]
Perhaps less beautiful, but vertical space is an issue with gnome.

On my laptop I use: ```.default-decoration.titlebar:not(headerbar), headerbar.default-decoration { padding: 4px; min-height: 0px; }```.

**Comment by lassekongo83** [comment]
It may be a controversial issue for some users. I have no idea how that would be received. I'm also not very keen in making any major changes to these themes as they already have a lot of users that may dislike change.
