### ISSUE TITLE
Issue in sound & brightness indicator (generating gresource) [gnome-shell]

### ISSUE THREAD

**Issue by sbsbs15** [lassekongo83/zuki-themes#141]
Hello, first of all I want to thank you for your work in the theme.

I've detected a problem in the colors shown in the sound and brightness indicators using the zuki-shell theme. If I set the theme in gnome tweaks the sound and brightness bar looks good, but generating a gresource file (using https://github.com/devpytech/gtk-gresource/) and setting it as the default gnome-shell theme the bar is not shown in the indicator popup.

![Screenshot from 2019-04-29 02-42-31](https://user-images.githubusercontent.com/15521217/56872364-96a2d280-6a28-11e9-8b1f-4418aa1e70b3.png)

I generate the gresource file in order to use the theme in GDM, so maybe you can consider providing support for the display manager (like other themes do) so that users could have a more complete experience.

Tested using the `v3.32-1` version of the theme and the latest commit in master (6db63941aeb1e81381235c5ab94e8989b8b97c91) in gnome-shell `3.32.1`.

Thanks!

**Comment by lassekongo83** [comment]
As for a gresource file. I don't use GDM, so I don't really know how it looks. Perhaps in the future though.

**Comment by sbsbs15** [comment]
Perfect!

Closed.
