### ISSUE TITLE
Side panel is white in some XFCE applications

### ISSUE THREAD

**Issue by pedrofleck** [lassekongo83/zuki-themes#142]
I'm using Zukitre (but Zukitwo have the same problem) with XFCE and it looks great, however, in some applications the side panel colour is white instead of light grey. In [Thunar](https://i.imgur.com/6B1MKwC.png), it just doesn't look as good as Nautilus (like [this](https://i.imgur.com/c3DOsVh.png) screenshot of Firefox download window that uses GTK3, but [Catfish](https://i.imgur.com/pjdodbZ.png), for example, looks buggy with grey text between white space.

**Comment by lassekongo83** [comment]
Fixed in https://github.com/lassekongo83/zuki-themes/commit/accfca538691b0faf72f649ab19990f916e081fe

**Comment by pedrofleck** [comment]
The updated theme is looking great, and Catfish is fixed, however, in Zukitwo, Thunar still have a white sidebar (Zukitre is fixed).
