### ISSUE TITLE
[SUPPORT] Checkbox/radiobutton colours

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#145]
I'd love to change the colour of checkboxes and radiobuttons to a dark grey shade. I assume that they're currently being set by the general highlight colour $selected_bg_color. But I'd like to keep the highlight colour blue.

Is there an easy way to define the colour of checkboxes/radiobuttons in the SCSS files?

**Comment by lassekongo83** [comment]
Can be changed in `_drawing.scss`. For example here: https://github.com/lassekongo83/zuki-themes/blob/5cc9f1ca1fa897848a681babf90825aa8bff1e23/gtk/src/Zukitre/gtk-3.0/_drawing.scss#L389
