### ISSUE TITLE
Nemo checkboxes/radiobuttons

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#146]
In Nemo, the colours of Checkboxes/Radiobuttons are black and not blue as in the actual theme. I've tested it with other themes and they work in Nemo (they affect the checkboxes/radiobuttons).
I am using the Zukitre theme.

Screenshot: https://imgur.com/leuoQag

I don't think that the other themes apply Nemo specific theming, because Adwaita works as expected with Nemo.

**Comment by lassekongo83** [comment]
That's the intended idea. Checkboxes in menus should be monochrome in this theme. However, the hovered state was white, and that has now been fixed.

**Comment by dglava** [comment]
I actually like that.
Thanks for fixing the hovered state.
