### ISSUE TITLE
Checkbox hover

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#147]
The hovered menuitem checkbox was fixed. But I've stumbled upon a similar issue, except that it's not in a menu item. Perhaps it's exclusive to Nemo, because I don't know where to find another checkbox constellation like that.

It can be found in Nemo under "Edit-Preferences-List Columns".

Here's a video of it:
https://dump.video/YvRG3J

- GTK version: 3.24.8+177+gae2ef1472c-1 (the one packaged by Arch).

**Comment by lassekongo83** [comment]
Working as intended. Those are list-boxes and not menus.

**Comment by dglava** [comment]
Thanks for fixing this.
