### ISSUE TITLE
No LightDM theme

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#148]
Perhaps I've done something wrong, but the LightDM theme doesn't seem to get built and installed.

In the `Zukitre/gtk-3.0` directory I only have `assets  gtk.css  gtk-dark.css`. Usually there used to be a LightDM CSS file as well. Is this a regression or did I screw the build up (I used the instructions in the README).

**Comment by lassekongo83** [comment]
It's in the gtk.css file. https://github.com/lassekongo83/zuki-themes/blob/master/gtk/src/Zukitre/gtk-3.0/gtk.css#L1876

**Comment by dglava** [comment]
My bad again, I forgot to change the theme name in the LightDM greeter config.

There's one small issue though, the text in the bar seems to be white on white, with a darker outline. Is this intended?

https://imgur.com/DfNw37W

**Comment by lassekongo83** [comment]
That's not intended, the panel is supposed to be dark. It has been a while since I've used any login manager, so I can't properly test it. May have to scrap the lightdm theme eventually.

**Comment by dglava** [comment]
That's unfortunate.

In case you decide otherwise, here's the upstream reference CSS guide for [lightdm-gtk-greeter](https://git.launchpad.net/lightdm-gtk-greeter/tree/data/sample-lightdm-gtk-greeter.css). You can conveniently test it by running it in a separate window with Xephyr `lightdm --test-mode`.
