### ISSUE TITLE
File-Roller background and other small things

### ISSUE THREAD

**Issue by dlyr** [lassekongo83/zuki-themes#157]
### Describe the issue

I find the background of the top tool bar in file-roller too dark. Do you know any way I can lighten it (without modifying the rest of the theme, which is fine).
I am quite new to theming, although I want to have a specific border for the titlebar of emacs. I try some things but could not get the point on how to select emacs titlebar only. When I enable emacs menu it's fine, but without menu, the titlebar merge with the text background (which I intentionally set to bg_color).
I have tweaked a little bit titlebars and button to make them more compact (see my [fork](https://github.com/dlyr/zuki-themes)) But it seems something prevent to reduce buttons (and header/title-bars even more) any guess ?

### Screenshot(s)
from top to bottom: emacs as I like it, without menubar, but missing a separation border line
emacs with menubar, the border line I want is here ;)
file-roller too black area, around the "home" button for instance.

![Capture d’écran de 2020-02-15 15-46-58](https://user-images.githubusercontent.com/11328509/74590036-07909680-500b-11ea-8c63-baed15f47b2b.png)

### Versions
- OS/version: Debian GNU/Linux bullseye/sid
- GTK+ and/or application versions: GNOME Shell 3.34.3

Thanks for your help.
++ dlyr

**Comment by lassekongo83** [comment]
Fixed.

**Comment by dlyr** [comment]
Thanks. Any advice on application specific css style (i.e. for emacs) or how to get tighter headerbars ?

**Comment by lassekongo83** [comment]
Try changing the paddings and min-heights of the `.default-decoration` class, and the same for any button classes within it.
