### ISSUE TITLE
Xfce4-notifyd theme white line

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#158]
### Describe the issue

In the Zukitre theme, there's a white line at the bottom of the notification. I don't know if it's intended to look this way. It doesn't look that bad, but I thought I'd report it just in case.

### Screenshot(s)
https://i.imgur.com/LSF6rFK.png

### Versions

OS/version: Arch Linux
GTK version: 3.24.18
Xfce4-notifyd version: 0.6.0

**Comment by ochosi** [comment]
Just as an FYI for @lassekongo83 : The fallback for the notifyd theming was changed to the keycap class (which has such a bottom border often times).
