### ISSUE TITLE
ubuntu software window on 20.04 is transparent

### ISSUE THREAD

**Issue by eduarddrenth** [lassekongo83/zuki-themes#160]
###
when using on of the zuki themes the window of ubuntu software is completely transparent. With for example yaru it's not.

### Screenshot(s)
![image](https://user-images.githubusercontent.com/10200360/81047660-2c363500-8ebb-11ea-9438-3a67b1cc082b.png)

### Versions

- OS/version: ubuntu 20.04
- GTK+ and/or application versions: 3.24.18-1ubuntu1

**Comment by eduarddrenth** [comment]
Other apps don't show this problem, might be a problem in the software app or in ubuntu.

**Comment by lassekongo83** [comment]
Could be because the snap-store is a snap application. But I don't have any installation to test with at the moment.

**Comment by lassekongo83** [comment]
I can not try check this myself, but if the theme isn't installed/available in `/var/lib/snapd/hostfs/usr/share/themes/`, then it may not be used in snap applications.

Bug on launchpad: https://bugs.launchpad.net/snap-store/+bug/1867417
According to that issue, the theme should default to Adwaita, but it doesn't. Snap-store beta channel may have a fix. (snap-store version 429+)

**Comment by eduarddrenth** [comment]
as a test copied /usr/share/themes to /var/lib/snapd/hostfs

The problem remains, it is not solved by this

**Comment by lassekongo83** [comment]
Try copying the theme to `~/.themes` as that's what required for flatpak apps to use 3rd party themes. May be the same for snaps.

**Comment by eduarddrenth** [comment]
noop
