### ISSUE TITLE
Asset build error with Inkscape 1.0

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#161]
Inkscape version 1.0 changed the CLI options. `--export-png` seems to have been deprecated. The new option seems to be `--export-filename`.

Building the assets with the `render-assets.sh` file fails because it's still using `--export-png`. Changing it to the new `--export-filename` fixes it.

**Comment by lassekongo83** [comment]
I'm still not on 1.0, so it will be fixed when I can use it myself. As those files are primarily used by developers I would suspect most developers can fix any incompatibilities themselves for the time being.
