### ISSUE TITLE
Theme parsing error Zukitre

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#163]
### Describe the issue

A Gtk-Warning message appears when using the theme. 
`Gtk-WARNING **: 12:14:55.525: Theme parsing error: gtk.css:1:432: negative values are not allowed.`

### Versions
- GTK+ versions: 3.24.20
- Zukitre version: latest build from master

**Comment by lassekongo83** [comment]
Did the latest build fix it?

**Comment by dglava** [comment]
Yes, the error message is gone. Thanks.
