### ISSUE TITLE
Is there a way to install the themes in the home directory?

### ISSUE THREAD

**Issue by touhouyouth** [lassekongo83/zuki-themes#165]
I need to somehow build and install the themes in the home directory, but I'm not familiar with ninja. What should I do?

**Comment by lassekongo83** [comment]
Tbh, I'm not as familiar with meson/ninja either. I would just suggest that you copy for example: `https://github.com/lassekongo83/zuki-themes/tree/master/gtk/src/Zukitre` to `~/.themes`

**Comment by touhouyouth** [comment]
The problem is that it isn't not built yet as you may see the folder called src (source). And there's no script to build it without installing.

**Comment by lassekongo83** [comment]
I added a script that you can use to install the theme locally.

**Comment by dglava** [comment]
You can do `DESTDIR=/home/you/.themes ninja -C build install`.
