### ISSUE TITLE
No dark theme for GTK+ 3?

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [lassekongo83/zuki-themes#24]
Would it be possible to create a dark (or at least, quasi-dark) variant of the Zukitre theme? This, in theory, shouldn't be terribly difficult, and should only require defining theme default colors as in gtk-main.css except in a *-dark.css file.

![screenshot from 2014-10-26 12 53 27](https://cloud.githubusercontent.com/assets/8833323/4783669/a2ad3ff2-5d30-11e4-8954-5ce4166a6e9f.png)

**Comment by lassekongo83** [comment]
Update to 3.18 fixes this.
