### ISSUE TITLE
LibreOffice styling (menus and toolbars)

### ISSUE THREAD

**Issue by sksmfjsduausjdfl** [lassekongo83/zuki-themes#25]
When LibreOffice menus are clicked/active, the font on them (i.e., on 'File', 'Edit' - whichever one is selected) becomes white.

Secondly, the toolbars look rather strange, and are separated by a thin trough.

Thirdly, if one looks carefully, the selected buttons (e.g. spelling/grammar check and left paragraph alignment) are also also appear slightly strangely, with with a thin, light, border on the top and bottom of the buttons.

Lastly, the drop-down arrows are not styled consistently, and feature a gradient as opposed to being flat, as in the GTK+ 3 version of the theme.

![screenshot from 2014-10-26 12 56 22](https://cloud.githubusercontent.com/assets/8833323/4783673/196f3bc2-5d31-11e4-8507-a8f803de6302.png)

**Comment by lassekongo83** [comment]
I think this is fixed in the latest Zukitre version. If not, open a new issue.
