### ISSUE TITLE
Evince Titlebar unevenly sized elements (3.14)

### ISSUE THREAD

**Issue by jthurner** [lassekongo83/zuki-themes#28]
The "page selector" and "zoom" fields are bigger/higher than the other elements. Comparing with Adwaita, It looks like these "widgets" (not sure if that is the correct term) are not getting scaled down, while the icons are.

Zukitwo:
![zukitwo](https://cloud.githubusercontent.com/assets/2171402/4843530/54980882-6033-11e4-962a-ccab86a8dfd9.png)
Adwaita:
![adwaita](https://cloud.githubusercontent.com/assets/2171402/4843529/54967094-6033-11e4-97b2-5ba53cd90c3c.png)

~~This is with the 2014.10.22 release.~~ Same with latest from git

**Comment by lassekongo83** [comment]
This should be fixed once the new version of Zukitwo for 3.18 arrives.
