### ISSUE TITLE
xfce system load bar-graph  doesn't show on xfce panel

### ISSUE THREAD

**Issue by sk1418** [lassekongo83/zuki-themes#29]
I use ArchLinux with xfce followings are the related softwares I installed
version info:
xfce4-panel 4.10.1
xfce4-systemload-plugin 1.1.1
aur/zukitwo-themes 20141022-1
GTK3 3.14

I set zukitwo as system theme. I add systemload monitor plugin (or networkmonitor) on a xfce panel,  no matter how did I set the monitor bar-graph color or panel bg color/ bg image (light, dark, transparent...), the bar was still empty. If I switched to other theme, the bars showed in right color.

I am having this problem for relative long time. And just because this, I chose other theme, but I like the zukitwo theme.  So I tested recently again, the problem still occurs.  Hope it could get solved.

**Comment by lassekongo83** [comment]
Should be fixed in the new Zukitre theme and upcoming Zukitwo theme for GTK 3.18 as the panel.rc has been rewritten.
