### ISSUE TITLE
Request: New Zuki theme with the Adwaita's colour pallete

### ISSUE THREAD

**Issue by sergioad** [lassekongo83/zuki-themes#30]
Hello @lassekongo83 as you have seen on the title I want ask you this: Can you make a Zukitwo exact clone but with the Adwaita colour pallete? I think this will look awesome and a good addition to the Zuki themes :smile:

**Comment by lassekongo83** [comment]
This can now be done by copying adwaita's _colors.scss and once you make your changes to the file, you can either run the ./parse-sass.sh script or keep SASS watching for changes as you
edit. This is done by running `bundle exec sass --watch --sourcemap=none .` If sass is out of date, or is
missing, you can install it with `bundle install`. (Requires ruby, gem, sass & bundle.)
