### ISSUE TITLE
Confirmation pop up color

### ISSUE THREAD

**Issue by kafran** [lassekongo83/zuki-themes#36]
![screenshot from 2015-02-25 12 44 38](https://cloud.githubusercontent.com/assets/1889828/6374811/112e67dc-bcf2-11e4-9bef-6b9c36cdcd64.png)

**Comment by wilfm** [comment]
It may help to add what version of Gnome, which theme, which window, what OS, etc

**Comment by kafran** [comment]
I'm sorry, I didn't know the useful information.

I'm on Fedora 21, Gnome 3.14.2, Zukitre + ZukiShell (lastest version from github), Window: Gnome Settings for Region and Language, it ask for a restart when change the input sources.

**Comment by wilfm** [comment]
Cool - Same setup, same issue here:
![screenshot from 2015-02-27 16 45 14](https://cloud.githubusercontent.com/assets/6739839/6416713/10818238-bea0-11e4-8d32-54be42e14673.png)

**Comment by tfhavingfun** [comment]
Try the fix above.

**Comment by lassekongo83** [comment]
Fixed in the new Zukitre beta release for Gnome 3.18.

**Comment by kafran** [comment]
Thanks. Is the Zukitre already usable within 3.18? How can I change the scroll bar to be square instead of rounded?

**Comment by lassekongo83** [comment]
It's usable on Gnome, just some xfce and gtk2 fixes needed. The scrollbar has changed to square on gtk3 applications.
