### ISSUE TITLE
GNOME 3.16 support?

### ISSUE THREAD

**Issue by strelec** [lassekongo83/zuki-themes#37]
Gnome 3.16 is out.

Is there any plans to make it work for this version, too? The theme looks quite right already, but a few details.

**Comment by wilfm** [comment]
Mainstream support it not quite available (of course it is available [for Arch](http://www.linuxveda.com/2015/03/24/how-to-test-gnome-3-16-on-arch-linux/), and it seems to have been release upstream anyways: https://mail.gnome.org/archives/gnome-announce-list/2015-March/msg00071.html ) - but Ubuntu you will probably need to use PPA's on the development version, & for Fedora you need 22 Alpha (or possibly backports to older versions), etc. Would be a great thing to have though :D

@strelec it might help to specify which details have issues.

**Comment by strelec** [comment]
When you delete something, the message "filename" deleted is white text in a translucent box - you are not able to see it.

Header bars for windows are enormous, even though the application doesn't use the new header style, like, say, nautilus does.

There are some more, though. I can't remember now.

**Comment by lassekongo83** [comment]
Whenever I feel I have the time I'll do some work on it. Need to learn scss unfortunately which is a complete pain to learn for me. So it will take some time before I have anything ready.

**Comment by mdeboer** [comment]
Would love to see some more work done to fix 3.16 support. Things don't look too bad right now but some things need fixing.

- Gnome Terminal has a strange shadow
![screenshot from 2015-04-11 10-31-09](https://cloud.githubusercontent.com/assets/1171956/7100805/34e9475c-e036-11e4-9c26-58cd7e155f53.png)
- Most applications (excluding ones that use a custom header like Nautilus) use the default minimize, maximize and close buttons instead of the theme's buttons
-Firefox theme is somewhat broken somehow, sides of an active tab are not how they used to be and have a different colour.
![screenshot from 2015-04-11 10-34-30](https://cloud.githubusercontent.com/assets/1171956/7100815/7234b74a-e036-11e4-98ce-e8db7bf6727c.png)

**Comment by Narrat** [comment]
and without a composite manager the shadow borders look like that
https://paste.archlinux.de/JVo/
Although not really sure if this a problem with the theme or the window manager

**Comment by mdeboer** [comment]
Having tried other themes like the Paper theme, these don't appear to have those kind of issues. Still, I think the Gnome team has some work to do on the theming part as there's some other bugs even with the default theme (Adwaita). For example, there's a line above every menubar, so ugly! Adwaita doesn't look as sleek as it used to and I don't feel like it was intended.

**Comment by questmark** [comment]
>@mdeboer 
Firefox theme is somewhat broken somehow, sides of an active tab are not how they used to be and have a different colour.

This might sound silly, but did you try restarting Firefox? I get those discolored tab edges too when I switch themes, but restarting Firefox gets rid of them.

@Narrat 
I'm getting the same border issue, with or without a compositor, so it's probably theme related.

**Comment by phyrog** [comment]
There are also some issues with the shell theme and the new notification area (default theme on the right for comparison).

![diff](https://cloud.githubusercontent.com/assets/2951180/7101802/3d5250c6-e06a-11e4-9015-f93e5e979f2a.png)

@mdeboer I also have that weird shadow with the Numix GTK theme (although it's not as visible as with the zuki theme)

**Comment by mdeboer** [comment]
@questmark well yeh, I thought of that too but that didn't seem to fix it for me unfortunately though I'll have another go as I'm not sure whether I have the latest version.

@phyrog what's wrong with it? I don't see anything odd :)

**Comment by phyrog** [comment]
@mdeboer Well, when you compare it to the GNOME 3.14 version of the shell theme, it does look a lot different.

![old](https://cloud.githubusercontent.com/assets/2951180/7101997/78b6f0ba-e072-11e4-95bc-ada1aec3d824.png)

So, one thing that are bothering me are the rounded backgrounds of dates (they are not even circles like in Adwaita, but are slightly elliptical), and there is a very thin border around dates that are not in the current month.

**Comment by mdeboer** [comment]
Well yes but that has just been a design choice with Gnome 3.16, I like it really. Let's first focus on fixing things.

**Comment by phyrog** [comment]
Regarding the window shadow issue I found this comment https://github.com/shimmerproject/Numix/issues/206#issuecomment-91518687 that seems to fix it for Zuki too.

**Comment by vitriol** [comment]
+1 for this one, can't wait to have it updated to 3.16, there are too few decent themes out there, this is like bread for me.

**Comment by bosaap** [comment]
just installed gtk 3.16.4 and the menu text has very ugly shadow/double vision blur

**Comment by DDZ57** [comment]
"Whenever I feel I have the time I'll do some work on it. Need to learn scss unfortunately which is a complete pain to learn for me. So it will take some time before I have anything ready."

-> Why not to organize a community development to distribute tasks among
several people for this nice theme rather than it depends on one author?

**Comment by arkhan** [comment]
Support to Gnome 3.18..?

**Comment by lassekongo83** [comment]
Started update to 3.18.
