### ISSUE TITLE
Title/Menu/Tool/Tab bars transition not seamless

### ISSUE THREAD

**Issue by Sadi58** [lassekongo83/zuki-themes#41]
One of the few 99% perfect themes, for instance far better than the default ones for Ubuntu.
But I think it would be 100% perfect if the transition between title/menu/tool/tab bars in some apps like gedit, thunderbird and synaptic were as seamless as in others like nautilus. Even gtk2 apps look better (although not %100 perfect) in that respect - e.g. Chrome, KKEdit, LibreOffice.
The screenshot below compares gedit and nautilus.
![zukitwo-bars](https://cloud.githubusercontent.com/assets/6375934/7514902/a4c7b3c6-f4ca-11e4-8da9-195a167df3e8.jpg)

**Comment by leigh123linux** [comment]
-1 to all that CSD nautilus shit!!!

**Comment by lassekongo83** [comment]
Main focus of development is now Gnome 3.18 and XFCE. On XFCE there are a couple of transitions I don't like, but it conflicts with Gnome where some of the transitions are needed. I may provide instructions on how to make the transitions seamless further on. Closing issue for now.
