### ISSUE TITLE
Can't Resize After Using Window Tiling Function in Cinnamon (Mint)

### ISSUE THREAD

**Issue by buster2209** [lassekongo83/zuki-themes#45]
When I go to resize the window when the folder is within the Window Tiling function, it makes the window width about a 1/4 of what it and is unmovable until it is released from the Window Tiling function.

After experimentation, it appears the Zukitwo 'Windows border' theme is the culprit.

**Comment by leigh123linux** [comment]
Mint is using a very old version of gtk (3.10) so expect issues as you need to have gtk-3.14 minimum to use Zukitwo.

**Comment by lassekongo83** [comment]
3.18 will now be required which I think will arrive in the next Linux Mint version. Cinnamon is however not supported. Closing issue as the new version of Zukitwo is in development. No fixes to the old one any more.
