### ISSUE TITLE
Gedit tabs issue

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#46]
Opening two or more tabs in Gedit creates a rather thick, white line/area below and above the text entry box. This affects Zukitwo on GTK 3.16.

Screenshot:
![](http://s27.postimg.org/rbjnsl6ir/2015_08_31_225452_807x642_scrot.png)

**Comment by lassekongo83** [comment]
Should be fixed once the new version of Zukitwo for Gnome 3.18 hits master branch.
