### ISSUE TITLE
GTK3 - incorrect minimize icon if you don't use all 3

### ISSUE THREAD

**Issue by Pshemas** [lassekongo83/zuki-themes#50]
I have only minimize and close buttons enabled (I'm used to using snaps for maximizing). I've noticed that on GTK3 apps (Gnome 3.14, Fedora 21) minimize icon is incorrect - it uses maximize icon instead (GTK2 apps got those correctly). Is there a way to fix it?

**Comment by lassekongo83** [comment]
3.14 is no longer supported. Try Zukitre for Gnome 3.18 and let me know if the issue still exist.
