### ISSUE TITLE
Inactive ComboBox text too light

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#51]
On GTK 3.18 the text for the drop down menus (ComboBoxes) is too light and it gives off the impression of being inactive or disabled. This affects Zukitwo.

Here's how it looks in Zukitwo, inactive and on hover/select:
![](http://s23.postimg.org/trf8f58u3/2016_03_13_11_21_59.png) 
![](http://s23.postimg.org/hqyds5qt7/2016_03_13_11_22_03.png)

Here's how the default Adwaita theme handles it:
![](http://s27.postimg.org/bn6ixrw9v/2016_03_13_11_29_50.png)

**Comment by lassekongo83** [comment]
Should be fixed once Zukitwo for 3.18 arrives. (Still in development.) In the meantime you can try Zukitre.
