### ISSUE TITLE
Deletion of old themes

### ISSUE THREAD

**Issue by anlutro** [lassekongo83/zuki-themes#52]
I see you've deleted some old themes from this repository.

May I suggest that you create one or more separate repositories for your old themes Zukitwo and Zukiwi?

I'm git cloning your repository and symlinking Zukitwo into my `~/.themes` directory. It's annoying having to `git checkout` a specific tag, rather than just doing `git pull` to make sure I'm up-to-date.

**Comment by lassekongo83** [comment]
Grab the old unsupported release from this tag: https://github.com/lassekongo83/zuki-themes/tree/v3.14-1

**Comment by anlutro** [comment]
I'm aware I can do that. I'm saying it'd be far more convenient if it was in a separate repository, or a separate branch, instead of a tag.

**Comment by lassekongo83** [comment]
I created a separate branch from that tag. If that will work with the cloning I don't know.

**Comment by anlutro** [comment]
Great. Thanks.
