### ISSUE TITLE
Font color is black for desktop icons

### ISSUE THREAD

**Issue by swarnendubiswas** [lassekongo83/zuki-themes#53]
The font color is black for all desktop icons, is this by design? In my opinion, black fonts on the desktop are harder to read.

![screenshot from 2016-04-06 22-44-42](https://cloud.githubusercontent.com/assets/7343807/14339028/51059a50-fc49-11e5-8d2c-8211bec4fc9b.png)

**Comment by lassekongo83** [comment]
Fixed in the latest commit.
