### ISSUE TITLE
xfce4-notifyd theme

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#54]
Selecting "default" as the theme for xfce4-notifyd, which uses the currently set GTK2 theme, results in this with Zukitre:

![zukitree theme](http://s29.postimg.org/x61ood1dz/2016_04_07_15_00_06.png)

The button's text is illegible. Would it be possible to include an xfce4-notifyd theme to fix this? Interestingly Zukitwo doesn't have this problem; using the values from its gtkrc gives us black text on a grey background button. Maybe this could be fixed in Zukitre's gtkrc without the need for an explicit xfce4-notifyd theme?

Example xfce4-notifyd themes:
![Greybird's](https://github.com/shimmerproject/Greybird/blob/master/xfce-notify-4.0/gtkrc)
Smoke, included in the xfce4-notifyd package: http://git.xfce.org/apps/xfce4-notifyd/plain/themes/Smoke/gtkrc

**Comment by lassekongo83** [comment]
Made some changes to it. Can't test it myself at the moment, so let me know if things look better or worse.

**Comment by dglava** [comment]
The button still looks the same.

![](http://s27.postimg.org/w37dsad2r/2016_04_07_16_48_11.png)

I also noticed that the progress-bar (only for GTK2, haven't tested GTK3) lost its angled stripes. Was that intentional or a bug caused by the latest change?

**Comment by lassekongo83** [comment]
What do you type into notify-send to get a button? Also, the progress-bar change was intentional. The gtk3 progress-bar doesn't have any stripes.

**Comment by lassekongo83** [comment]
Nvm, got xfce4-notifyd-config. I tested the button now and my button is styled. Try reloading the theme or desktop. However, I need to fix the border of the button.

**Comment by dglava** [comment]
It looks great now. Thank you!

![](http://s18.postimg.org/4z01kdoo9/2016_04_07_22_24_22.png)
