### ISSUE TITLE
Scrollbar colors

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#55]
Clicking and starting a drag on the scrollbar (GTK3 theme) causes it to flash very briefly. Was this a deliberate choice for Zukitre?

Right now the scrollbar goes through:
idle; color 1
hover; color 2
click; color 3 <--- Short blue highlight color flash
drag; color 1
release; color 2
stop hovering; color 1

[Example video](http://webm.land/media/CZMK.webm)

The quick flash looks unnecessary and almost like a glitch. Personally, I love the GTK2 theme's simple 2-color scrolling and find it way less distracting. It would be sweet if the GTK3 bars could behave in a similar, simpler way.

**Comment by lassekongo83** [comment]
It's not supposed to flash. For me it stays blue when I hold the slider. But I think I'll remove the blue and just use the same color for pressed and hover.
