### ISSUE TITLE
Space between titlebar buttons.

### ISSUE THREAD

**Issue by mrlamud** [lassekongo83/zuki-themes#57]
I'm sorry to bother you.
How can I reduce space between titlebar buttons. I feel like it's a bit too much space between each buttons.

**Comment by lassekongo83** [comment]
If you mean the min, max, close buttons.
_button.titlebutton { min-width: 20px; }_ will the reduce the space a little bit.

Default is set at 24px, but any lower value than that will probably cut a couple of pixels from the image asset.
