### ISSUE TITLE
[Feature Request] Budgie support

### ISSUE THREAD

**Issue by ghost** [lassekongo83/zuki-themes#58]
This is how Budgie looks using Zukitre:

![captura de pantalla de 2016-04-15 23-06-42](https://cloud.githubusercontent.com/assets/12128317/14578464/65760c14-035f-11e6-9376-c84376b011a6.png)

You can find how to theme Budgie looking at the [Vertex](https://github.com/horst3180/vertex-theme/search?utf8=%E2%9C%93&q=budgie) code :smile:.

**Comment by bmeznarsic** [comment]
I suggest you close this. The Solus project is porting the desktop components to Qt. https://budgie-desktop.org/2017/01/25/kicking-off-budgie-11/
