### ISSUE TITLE
Missing fonts in fresh install of 16.04

### ISSUE THREAD

**Issue by Beefalo** [lassekongo83/zuki-themes#60]
I am on fresh install of ubuntu-gnome 16.04. When I active zuki-shell theme I see white boxes instead of letters/numbers in shell. 
See screenshot: http://imgur.com/uVqXncT

Yes, I did install fonts-roboto :).

**Comment by lassekongo83** [comment]
I can't reproduce this in my 16.04 vm. Do you use any cyrillic or asian letters as default? What's your DPI and hinting settings?

**Comment by Beefalo** [comment]
All defaults are en-US or de-DE. How can I see DPI and hinting settings?

**Comment by lassekongo83** [comment]
'Typing' in gnome-tweak-tool.

**Comment by Beefalo** [comment]
I guess I toyed too much around now. Installing roboto-unhinted and re-installing roboto-hinted fixed the problem. Will try too reproduced when I find some spare time on a clean install with more information. WIll close this until then. Thanks for help!!

**Comment by lmillefiori** [comment]
Upgraded to 16.04 and I am having a similar problem, see the top bar in the screenshot: [http://imgur.com/a/OWU6W](http://imgur.com/a/OWU6W), the font is clearly not Roboto. 

In my case, the solution was to change the font family in [gnome-shell-sass/_common.scss#L31](https://github.com/lassekongo83/zuki-themes/blob/master/Zuki-shell/gnome-shell/gnome-shell-sass/_common.scss#L31) from `Roboto` to `Roboto Regular`: [http://imgur.com/a/4EQwP](http://imgur.com/a/4EQwP), or directly in the CSS.
