### ISSUE TITLE
GTK Theme not working

### ISSUE THREAD

**Issue by kneeki** [lassekongo83/zuki-themes#61]
Hello,

Here's a screenshot of what the theme looks like once I enable it using the tweak-tool.
http://imgur.com/m4MuJJH

As I'm new to themes; I'm sure I'm missing something simple. Using Ubuntu 16.04 I've installed the Zuki themes to `~/.themes` and ensured I have all the requirements installed. I've also ensured that I have the proper version of GTK installed:
```sh
dave@Dave-MacBookAir:~$ apt-cache policy libgtk2.0-0 libgtk-3-0
libgtk2.0-0:
  Installed: 2.24.30-1ubuntu1
  Candidate: 2.24.30-1ubuntu1
  Version table:
 *** 2.24.30-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
libgtk-3-0:
  Installed: 3.18.9-1ubuntu3
  Candidate: 3.18.9-1ubuntu3
  Version table:
 *** 3.18.9-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

Any ideas as to where I've gone wrong?

**Comment by lassekongo83** [comment]
Did you download the right version of the theme? Master branch is for GTK 3.20. The 3.18 branch can be found here: https://github.com/lassekongo83/zuki-themes/tree/3.18

**Comment by kneeki** [comment]
Well there we go. Downloading the 3.18 version of the theme seemed to work perfectly. Would you recommend updating GTK to 3.2?

**Comment by lassekongo83** [comment]
I suggest you use GTK 3.18 for Ubuntu 16.04 LTS as that's what is being supported in that release.
