### ISSUE TITLE
Hovering scrollbar on a WebKitWebView makes grow thicker

### ISSUE THREAD

**Issue by aperezdc** [lassekongo83/zuki-themes#62]
When hovering with the mouse over a scrollbar in Epiphany (which uses WebKitGTK+), the scrollbar will get thicker than in normal (non-hovered) state. This happens bothj with vertical and horizontal scrollbars, and also with scrollbars nested in an `<iframe>` or in an HTML element which has `overflow: scroll`  in its CSS rules.

![screenshot from 2016-04-25 19-57-50](https://cloud.githubusercontent.com/assets/723451/14791833/3d776e10-0b20-11e6-996e-b76f3a80b003.png)

**Comment by aperezdc** [comment]
For reference, I am using the current `master` from Git, under Arch Linux, with the following package versions:

* GTK+ 3.20.3-1
* WebKitGTK+ 2.12.1-1
* Epiphany 3.20.1-1

**Comment by lassekongo83** [comment]
Seems to be an issue with WebKitGTK. Setting _ -GtkScrollbar-has-backward-stepper_ and _-GtkScrollbar-has-forward-stepper_ to true seems to cause this issue in any theme. I'll suggest you report this at the WebKitGTK/Epiphany bug tracker.

**Comment by aperezdc** [comment]
Done, I have [reported the bug upstream](https://bugs.webkit.org/show_bug.cgi?id=156988), thanks for the feedback!
