### ISSUE TITLE
Default buttons?

### ISSUE THREAD

**Issue by petrucci4prez** [lassekongo83/zuki-themes#63]
The older gtk3.14 Zuki themes had blue default buttons and I thought they were a nice touch. These don't seem to be themed at all right now.

This is obviously more of an aesthetic question, but is there a reason these have not been carried over to the newer themes?

**Comment by lassekongo83** [comment]
I think the .default css class has been deprecated. I really don't know how to get it to work any longer.

**Comment by petrucci4prez** [comment]
Are you sure? I just tried this using gtk-inspector to look at the gtk3-widget-factory (which I assume would be up-to-date to work with the latest theme selectors). Was able to theme the default button on the file chooser with "button.default" selector in the live css editor.

Did the devs actually announce that this class was depreciated?

**Comment by lassekongo83** [comment]
When I add button.default it doesn't do anything. No change in color anywhere.

**Comment by petrucci4prez** [comment]
now I'm confused. This is what I got, and it will work on any file chooser (gedit, geany, widget-factory, etc)

![select a file_125](https://cloud.githubusercontent.com/assets/6629118/14837872/1448ae12-0bea-11e6-97dc-3392c6854444.png)

![gtk3-widget-factory_123](https://cloud.githubusercontent.com/assets/6629118/14837879/1a747078-0bea-11e6-9b70-15104d1f8eaa.png)

Exact package is gtk-3.20.3; are you using Arch to test these?

**Comment by lassekongo83** [comment]
Ah, so it's the file choosers. My buttons in file choosers are already blue. But they're in the headerbar of the file chooser. (I'm on gtk-3.20.3 as well.) I will test a new style on suggested buttons and then probably carry them over to the button.default style.
