### ISSUE TITLE
[FEATURE REQUEST] LightDM GTK Greeter theme

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#65]
Are there plans to add a lightdm-gtk-greeter theme?

Currently it looks like [THIS](http://s32.postimg.org/h7bd2hcr9/kek.png). It looks decent enough, but maybe it could be spiced up a bit?

I don't know if these guidelines still apply for GTK 3.20, but it might be helpful:
[For Theme Designers section](https://smdavis.us/2013/06/03/lightdm-gtk-greeter-1-6-0-released/) 
[Greybird reference LightDM GTK Greeter theme](https://github.com/shimmerproject/Greybird/blob/master/gtk-3.0/apps/lightdm-gtk-greeter.css)

**Comment by lassekongo83** [comment]
Added some quick lightdm css from the Arc theme. I use xinit though so I can't test it. Let me know if it looks bad.

**Comment by dglava** [comment]
It kind of [does](http://s32.postimg.org/doj3puh1x/kek.png). :smiley:

You can install lightdm, the gtk greeter and xorg-xephyr to [run/test](https://wiki.archlinux.org/index.php/LightDM#Testing) lightdm in a standard Xorg window.

**Comment by dglava** [comment]
It looks good now. Just one tiny suggestion:
Would it be possible to decrease the username font size so it matches the login button?

```css
#login_window #user_combobox {
  color: $fg_color;
  font: 13px; /* delete this line */

  menu { font: normal; }
}
```
