### ISSUE TITLE
GS OpenWeather Extension Has Bad Theming

### ISSUE THREAD

**Issue by nuliukas** [lassekongo83/zuki-themes#66]
As you can see, the OpenWeather gnome-shell extension has some strange theming with Zuki-shell. Gnome 3.18 here. I can definitely live with it, but on the other hand, it looks just fine with Adwaita. Thought maybe you would like to be aware of this.

Actually, I'm not even sure if this is something one could or should fix in the Zuki theme. Having said that, I'll take the chance by reporting it here.

With Zuki-shell:
![ekrano nuotrauka is 2016-05-03 16-08-50](https://cloud.githubusercontent.com/assets/10675691/14985833/7b51d782-1149-11e6-9a6b-dd703bf01a31.png)

With Adwaita:
![ekrano nuotrauka is 2016-05-03 16-15-36](https://cloud.githubusercontent.com/assets/10675691/14986007/5aa3af5a-114a-11e6-9a37-8c8b343e7f89.png)

**Comment by lassekongo83** [comment]
Should be fixed now. Let me know if it isn't.
