### ISSUE TITLE
LibreOffice GTK2 checkbuttons

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#67]
The checkbuttons in LibreOffice (using the GTK2 version) are white on a grey background, which makes them hard to spot. It's similar to this issue #43.

[Zukitre](http://s32.postimg.org/pm2ewl405/image.png)
[Adwaita](http://s32.postimg.org/oovznpshx/wa1.png)

**Comment by lassekongo83** [comment]
Try the new commit. I've completely rewritten the GTK2 style and based it on Greybird.

**Comment by dglava** [comment]
They're visible nicely now.

A couple of new inconsistencies popped up. For example the menus have a different background white shade for GTK2 and GTK3.

[GTK2](http://s32.postimg.org/xc464c0at/2016_05_07_124920_1280x800_scrot.png) has a brighter #fdfdfd (which weirdly doesn't appear anywhere in the gtkrc)
[GTK3](http://s32.postimg.org/48bcucmth/2016_05_07_125000_1280x800_scrot.png) has #f7f7f7 (which IMHO looks nicer because the contrast isn't that high compared to the darker grey around it)

Is this a deliberate choice? If not, should I open a new issue for these since the LibreOffice thing is solved?

**Comment by lassekongo83** [comment]
Menus should now use the same base_color (#f7f7f7). Would like to fix the border too, but it seems to be hardcoded in the murrine engine.
