### ISSUE TITLE
Xfce4-notifyd progress bar

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#68]
The recent GTK2 changes messed up the progress-bar notifications for xfce4-notifyd.
No matter which value it's displaying, the bar just displays a black line. [Screenshot](http://s32.postimg.org/9fn828rwl/2016_05_07_15_15_52.png).

You can use `notify-send "Volume" -i audio-volume-high -h int:value:50` to test the progress-bar visuals.

**Comment by lassekongo83** [comment]
Should be fixed now.
