### ISSUE TITLE
[Feature Request] Bring back alternate row colors

### ISSUE THREAD

**Issue by gotmanyacc** [lassekongo83/zuki-themes#69]
Right now when I use a file manager (pcmanfm, thunar, nautilus...) with list view or detailed view this is what is lookes like:
![actualbehaviour](https://cloud.githubusercontent.com/assets/16804904/15334953/b65f1f26-1c46-11e6-8007-e7f8dd32bec1.png)

On older versions of this theme we had alternate row colors like these:
![desiredbehaviour](https://cloud.githubusercontent.com/assets/16804904/15334962/bc6451de-1c46-11e6-8e7a-5dcc0f5b084d.png)

Would it be possible to bring back this behavior for either Zukitwo or Zukitre?

**Comment by lassekongo83** [comment]
I removed it in GTK2 apps because it's not possible in GTK3. Want it to look unified between the 2.
