### ISSUE TITLE
Overlapping text in Ubuntu

### ISSUE THREAD

**Issue by p2635** [lassekongo83/zuki-themes#72]
Hi I'm a linux newbie who just installed Ubuntu and zuki.

Everything looks fine so far however I noticed overlapping text below when browsing the file manager, did I install it wrong?

![screenshot from 2016-05-26 21-02-16](https://cloud.githubusercontent.com/assets/4522927/15588703/03a7357e-2387-11e6-88e7-7f6d512fcfb1.png)

**Comment by dglava** [comment]
Did you install the 3.20 (from the master branch) or the 3.18 version of the theme?

Ubuntu 16.04 is using GTK 3.18, so you'll need [this](https://github.com/lassekongo83/zuki-themes/tree/3.18) branch of the Zuki-themes.

**Comment by lassekongo83** [comment]
That's the floating-bar. As ubuntu uses nautilus 3.14 the css class name may not be the same as the one in 3.18/3.20. But if you upgrade nautilus to 3.18/3.20 (at your own risk) in ubuntu, the floating-bar will have a background.
