### ISSUE TITLE
Nemo issues

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#73]
I don't know what your policy is about adding application specific CSS, but I thought I'd report it anyway.

It seems like Nemo [added custom style classes](https://github.com/linuxmint/nemo/issues/1150#issuecomment-213936948), which results in the file-rename box becoming invisible, without any hints of the current cursor/selection position when using a "non-compatible" theme (including the default Adwaita theme).

[Renaming with Zukitre](http://s33.postimg.org/jbvs2kca7/2016_06_02_17_58_00.png)
[Renaming with the Arc-theme which apparently has a style for this](http://s33.postimg.org/8rlujz7sf/2016_06_02_18_10_34.png)

The 2nd minor issue is the gray colored box in the lower part of the sidebar.

[Link](https://github.com/linuxmint/nemo/issues/1173) to the upstream Nemo bug report related to this.

**Comment by lassekongo83** [comment]
Fixed the first issue.

As for the second minor issue it feel like I've tried everything. I just can't get any color to change in that sidebar. I'm obviously missing something, but it's giving me a headache.

**Comment by dglava** [comment]
Thanks for fixing the renaming style.

Have you tried using the GTK Inspector to get additional information about the sidebar? You can run it with `GTK_DEBUG=interactive nemo`. I don't know what to look for in there, but you might find it useful. Apparently that thing is the GtkDrawingArea widget.

[Screenshot](http://s33.postimg.org/ipm24iogv/2016_06_02_22_28_21.png)

**Comment by lassekongo83** [comment]
Yeah, inspector is used. But I've even tried some of the fixes found [here](http://git.mate-desktop.org/mate-themes/tree/desktop-themes/BlueMenta/gtk-3.0/other-applications.css?id=c19e45eb330ba4219ed37fe6a2fecb4b39f22623) for the sidebar, and none are working.

**Comment by dglava** [comment]
Killing just Nemo's process and restarting it worked fine for me. But then again I'm not using the whole Cinnamon desktop.

Either way, thanks for fixing this. It looks great now.
