### ISSUE TITLE
Gno-Menu's popup not alaigned on Zuki shell

### ISSUE THREAD

**Issue by sergioad** [lassekongo83/zuki-themes#75]
Hello friends I used the Zuki shell theme and saw that the Gno-Menu's pop up is disalaigned to the screen and that this issue can be fixed by tweaking the theme (I noted that by using the adapta theme) could you fix the position of the Gno-Menu's pop up for Zuki shell please?

![captura de pantalla de 2016-06-11 09-50-24](https://cloud.githubusercontent.com/assets/5375145/15985759/840ca7fc-2fbd-11e6-9660-ed66f11751b1.png)
Here is how the zuki themed Gno-Menu looks

![captura de pantalla de 2016-06-11 10-20-16](https://cloud.githubusercontent.com/assets/5375145/15985785/3031ca12-2fbe-11e6-9643-94974d691fd2.png)
And here the Adapta theme

As you can see the issue can be solved, if you solve it please let me know because I LOVE the Zuki shell theme and because of that I want to use it with the Gno-Menu's pop up alaigned :smile:

**Comment by lassekongo83** [comment]
The popup menu alignment had been bugging me for some time too. Didn't realize it was as simple as changing a single value. Not perfect on all menus, but more acceptable on gno-menu at least.

**Comment by sergioad** [comment]
thank you very much :smile:
