### ISSUE TITLE
GTK 3.20 (XFCE): Zukitwo - The menu item focus (selection) is barely visible

### ISSUE THREAD

**Issue by kepler2** [lassekongo83/zuki-themes#76]
Hello. I appreciate this theme. I've found that a good combination is Elementary Icons with the Zukitwo theme :)

Ok, i've found a thing. If you select any menu item (File, Edit etc.) the selection is barely visible. In zukitre, the selection looks ok.

I think that the selection must be easier to see.

Please check out the screenshot below:

![zukitwo menu](https://cloud.githubusercontent.com/assets/18610924/16176203/d3eba990-3610-11e6-920f-e12b9ef84658.jpg)

Thanks

**Comment by lassekongo83** [comment]
Let me know if the colored border made any difference. Same thing Adwaita uses.

**Comment by kepler2** [comment]
Cheers. A Blue underline is now visible when a menu item is selected.
