### ISSUE TITLE
Re. tint2

### ISSUE THREAD

**Issue by philiparvidsson** [lassekongo83/zuki-themes#78]
Hi lassekongo83 - sorry for posting this here, I could not find another way to contact you! This issue is NOT related to your work, but rather a configuration issue. Would recommend that you setup a mail for direct contact here on github.

I'm using Ubuntu 16.04 LTS and cannot get tint2 to work properly. First off, the bottom panel is shortened and not shown below the tint2 clock as in your screenshot. Secondly, the tint2 tray does not work (it says another systray already exists). Thirdly, how would one go about donating to you? Thanks!

**Comment by lassekongo83** [comment]
1. See: https://www.reddit.com/r/unixporn/comments/4dkzqo/gnome_oc_updated_one_of_my_old_themes/d1ykm44 and also select to expand the dash to dock extension.
2. I don't use a tray, so can't help you there.
3. I have nothing setup for donations at the moment.

**Comment by philiparvidsson** [comment]
![screenshot from 2016-07-01 11-06-01](https://cloud.githubusercontent.com/assets/1163299/16517116/11ee0c82-3f7c-11e6-8986-2b71be2a595f.png)

The problem is that even though I've moved the applications icon to the start of the dock and have set the dock to expand to the screen edges, tint2 hinders the dock from expanding further. See image. Do you know what the problem is?

**Comment by lassekongo83** [comment]
Har inte det problemet. Kolla under inställningarna i tint2conf Panel > Window manager interaction. Kanske finns nån inställning där som kan åtgärda problemet.
