### ISSUE TITLE
A way to change colors?

### ISSUE THREAD

**Issue by tliron** [lassekongo83/zuki-themes#79]
Love Zuki! Would love a way to change colors, even if it involves building manually using autoconf (and likely having Inkscape or similar installed).

**Comment by lassekongo83** [comment]
You'll need ruby-sass and ruby-bundler. Modify the _colors.scss file and then run parse-sass.sh. Gtk2 color modifications can be done in the /gtk-2.0/gtkrc file. More info in the readme file here: https://github.com/lassekongo83/zuki-themes/blob/master/Zukitwo/gtk-3.0/README
