### ISSUE TITLE
Window control buttons look out of place with Totem

### ISSUE THREAD

**Issue by swarnendubiswas** [lassekongo83/zuki-themes#80]
This is an excellent theme, thanks. I am glad that you have updated Zukitwo to 3.20.

One glitch that I noticed is with the rendering of the window control buttons with Totem on Ubuntu Gnome. The buttons look a bit of out of place, and the pictures seem a bit grainy. I am using Gnome 3.20.

![screenshot from 2016-07-09 23-30-42](https://cloud.githubusercontent.com/assets/7343807/16711514/be37d0a6-462d-11e6-9fca-a38a0133d1c2.png)

**Comment by lassekongo83** [comment]
Seems that the Ubuntu unity titlebar patches leaks into the other DEs as well. It should be using a client side decoration by default. What happens if you remove the Zukitwo/metacity-1 folder and restart the application? What happens if you start totem with this command? `env XDG_CURRENT_DESKTOP=GNOME totem`

**Comment by swarnendubiswas** [comment]
Both suggestions work. Deleting metacity-1 possibly fallback to Adwaita controls. Specifying `env XDG_CURRENT_DESKTOP=GNOME totem` shows the CSD decoration. Was I able to explain or do you need snapshots?

**Comment by lassekongo83** [comment]
Add that command to any application that uses the wrong titlebar. You can add arguments in the `.desktop` files in `/usr/share/applications/`. So totem.desktop would have the following change:

Exec=env XDG_CURRENT_DESKTOP=GNOME totem

I'll report this issue upstream to the Ubuntu GNOME maintainers (if it hasn't been already). There's nothing I can do theme-wise to fix Canonical's titlebar patches.

**Comment by swarnendubiswas** [comment]
Thanks for your help. Reporting to Ubuntu Gnome sounds good.

**Comment by lassekongo83** [comment]
Btw, do you have the ubuntu-gnome-desktop meta package installed? You can check with `apt search ubuntu-gnome-desktop`. Or did you just install Gnome from another version of Ubuntu 16.04?

XDG_CURRENT_DESKTOP=GNOME is a variable they've set globally they say. Something may be broken with it if you use Gnome 3.20 though.

**Comment by swarnendubiswas** [comment]
Yes I have it installed. Although I have installed and uninstalled it several times earlier for manipulating packages. On a separate note, I hate all the unrelated packages that it pulls in.

Yes, I used the staging ppa to upgrade to 3.20. 

Do you know how can I set the variable globally, or check whether it is indeed set? I use fish as my default shell, I am not sure whether that can be a reason.

**Comment by lassekongo83** [comment]
`printenv | grep XDG` and see if there's anything set to Unity there. Haven't figured out any way to change it globally yet though, but it should be possible.
