### ISSUE TITLE
BIG buttons on synfig

### ISSUE THREAD

**Issue by jEsuSdA** [lassekongo83/zuki-themes#81]
Here, you can see Synfig with huge tabs buttons:

![screenshot58](https://cloud.githubusercontent.com/assets/5833446/17323967/7efecbae-58a4-11e6-8d74-d91c86f7c908.png)

The correct size is some like that:
http://synfig.org/1.0/overview/wp-content/uploads/2015/04/screenshot-07.png?5534dc

Great themes!
Thank you for your work! ;)

**Comment by lassekongo83** [comment]
Seems to be an issue with the program itself on GTK+ 3.20. More info: http://www.synfig.org/forums/viewtopic.php?t=10085

**Comment by jEsuSdA** [comment]
I solved this adding this rules to the gtk-contained.css:


window > box > widget > paned > paned > paned > notebook > header > widget > button,
window > box > widget > paned > paned > notebook > header > widget > button 
{
  min-height: 2px;
  min-width: 2px;
  height: 2px;
  width: 2px;
}

It works perfectly! ;)

**Comment by lassekongo83** [comment]
Seems to be fixed in Synfig master branch: http://www.synfig.org/forums/viewtopic.php?t=10085#p32955
