### ISSUE TITLE
[Question] Hoy can y change the selected tab background color?

### ISSUE THREAD

**Issue by jEsuSdA** [lassekongo83/zuki-themes#82]
Hi!

I like zuki themes, but I want to change the WHITE color of selected tabs to another.

¿How can I do it?
I'm not capable to find any "selected tab" code portion on the CSS files or GTK2 files.

Thank you.

**Comment by lassekongo83** [comment]
GTK3:
`notebook tab:checked { 
background-color: lightblue;
}`

GTK2:
`style "notebook-bg"
{
    bg[SELECTED] = shade (1.18, #000000)
}`

**Comment by jEsuSdA** [comment]
Thanks!

I could change the GKT2 styles doing this:

`
# style "notebook-bg"
# {
    # bg[NORMAL]   = shade (1.18, @bg_color)
    # bg[ACTIVE]   = shade (1.0, @bg_color) # Inactive tabs
    # bg[PRELIGHT] = shade (1.18, @bg_color)
    # bg[SELECTED] = shade (1.18, @bg_color)
    # fg[ACTIVE]   = mix (0.8, @fg_color, shade (0.97, @bg_color))
# }

style "notebook-bg"
{
	bg[NORMAL] = shade (1.05, @bg_color)
	bg[ACTIVE] = shade (0.97, @bg_color)
	fg[ACTIVE] = mix (0.8, @fg_color, shade (0.97, @bg_color))
}

`

Using   style "notebook-bg" { bg[SELECTED] = #000000 } does not work at all.


The GTK3 solution does not work and I can't find any solution.

Thanks!!!
