### ISSUE TITLE
Thin buttons on Firefox 48

### ISSUE THREAD

**Issue by dglava** [lassekongo83/zuki-themes#83]
Since Firefox version 48 (built with GTK3), the buttons are looking rather thin. The default GTK3 theme, Adwaita, doesn't have this problem; the buttons have more padding around them.

GTK version: 3.20.8
Firefox version 48
Distribution used: Arch Linux

Screenshot with Zukitre:
https://s10.postimg.org/cd3x165ex/2016_08_08_14_20_08.png

Screenshot with Adwaita:
https://s10.postimg.org/rkjwlix9l/2016_08_08_14_11_09.png

**Comment by lassekongo83** [comment]
I hope the fix doesn't screw up any other applications. Decreased the button min-height to 20px (which Firefox doesn't seem to use) and increased the padding to 4px.
