### ISSUE TITLE
Invisible window buttons in item preview - GNOME 

### ISSUE THREAD

**Issue by hliasa** [lassekongo83/zuki-themes#84]
Can't find any related issue posted here.
While I was using Nautilus and pressed space to preview an item, the pop up window did NOT have window buttons. They were there, but they were not styled.
![2016-08-10 11-41-34](https://cloud.githubusercontent.com/assets/15366357/17547456/fc1fd208-5eef-11e6-8e20-361b97ee5f7d.png)
-GNOME Shell 3.18.5
-Ubuntu GNOME 16.04.1

**Comment by lassekongo83** [comment]
I've figure out why the window control buttons aren't styled. The color on .close .minimize and .maximized is set to transparent to allow me to use png buttons on all other windows. I have found no way of styling gnome-sushi's header-bar as it doesn't have any application specific styles.

**Comment by pedrofleck** [comment]
It seems to be fixed on 3.28 (Arch Linux, Zuki-two)
