### ISSUE TITLE
Consider making a new release

### ISSUE THREAD

**Issue by GLolol** [lassekongo83/zuki-themes#85]
I'm interested in packaging the Zuki themes in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834278), but a lack of up-to-date tags makes it complicated to fetch specific versions of sources. Please consider making a new tag/release for GTK+ 3.20!

**Comment by lassekongo83** [comment]
[Done.](https://github.com/lassekongo83/zuki-themes/tree/3.20)

**Comment by GLolol** [comment]
Oh, I meant a new entry on the [release page](https://github.com/lassekongo83/zuki-themes/releases), because specific tags are easier to track (GitHub provides a tarball download for example).

**Comment by lassekongo83** [comment]
Is this better? https://github.com/lassekongo83/zuki-themes/releases

**Comment by GLolol** [comment]
Yes, thank you!
