### ISSUE TITLE
The themes are very ugly with Geany

### ISSUE THREAD

**Issue by ShyPixie** [lassekongo83/zuki-themes#91]
The themes are very ugly with Geany (1.28, Gtk3 version).

The first problem is that the color of the scroll bars are different from other applications with Zukitre theme:

![1](http://i.imgur.com/oFwUqJ9.png)

The second problem is a black square that appears in the corner of the window while i'm writing (with zukitre and zukitwo):

![2](http://i.imgur.com/KmbVfKq.png)

Third problem is a very  annoying flood that appears in my console when I move the scroll bar (with both themes):

```
[..]
(geany:21471): Gtk-WARNING **: for_size smaller than min-size (25 < 28) while measuring gadget (node tabs, owner GtkNotebook)

(geany:21471): Gtk-WARNING **: for_size smaller than min-size (25 < 28) while measuring gadget (node tabs, owner GtkNotebook)

(geany:21471): Gtk-WARNING **: for_size smaller than min-size (25 < 28) while measuring gadget (node tabs, owner GtkNotebook)
[...]
```

**Comment by jEsuSdA** [comment]
I don't have these problems.

Geany 1.28
Latest Zukitre
GTK 3.20

;)
![screenshot46](https://cloud.githubusercontent.com/assets/5833446/18348870/3aa34236-75ce-11e6-87a4-67c9202e9fc8.png)

**Comment by ShyPixie** [comment]
@jEsuSdA your geany is compiled with support to Gtk3?

**Comment by jEsuSdA** [comment]
Is a GTK2 compilation.

[000:000] Browser toolkit is Gtk2.
[000:001] Using Gtk2 toolkit


Sorry! ;)
