### ISSUE TITLE
Ugly black lines in firefox menus

### ISSUE THREAD

**Issue by VulkHead** [lassekongo83/zuki-themes#92]
Both zuki-themes have them. 
![screenshot from 2016-10-15 16-01-01](https://cloud.githubusercontent.com/assets/11966520/19413061/86e18bd6-92f1-11e6-9fa3-a098e6afcf34.png)
I don't know if I'm the only one with this problem but is kinda annoying, other themes doesn't have them.
Adapta:
![screenshot from 2016-10-15 16-09-53](https://cloud.githubusercontent.com/assets/11966520/19413078/f9e2fd4a-92f1-11e6-8fbd-cd8b8ce2e895.png)
Flat-Plat (Slightly Noticeable):
![screenshot from 2016-10-15 16-13-07](https://cloud.githubusercontent.com/assets/11966520/19413106/9b8c5a10-92f2-11e6-95dc-13c9d0205d6d.png)

Personally I like the one without lines (Adapta), looks very nice and clean.

**Comment by intdel** [comment]
Did you install the requirements? If you launch firefox from the console, does it give you any GTK errors?

**Comment by VulkHead** [comment]
Yes requirements are installed except `ttf-roboto`. Terminal logs these GTK errors:
![screenshot from 2016-10-19 13-36-18](https://cloud.githubusercontent.com/assets/11966520/19530333/741e2f82-9601-11e6-9a01-be33f04fbe7e.png)

**Comment by lassekongo83** [comment]
Added a menu fix. I don't like the method used, but it should get the job done. Hoping for no side effects. Also the arrows in the menus were white and still are if you hover them. New weird glitch that shouldn't happen.
