### ISSUE TITLE
cutted Synaptic toolbar background in Zukitre

### ISSUE THREAD

**Issue by jEsuSdA** [lassekongo83/zuki-themes#98]
Hi!

The synaptic toolbar does is cut and the background does not fills the entire width of window.
Here you can see how the dark grey background is broken after the Search button.

![screenshot1](https://cloud.githubusercontent.com/assets/5833446/20436091/0b036268-adaf-11e6-9f68-82e007067a2d.png)

Thank you so much for you work.
This theme is great!

**Comment by pedrofleck** [comment]
I don't know since when, but at this moment this problem seems to be fixed: https://i.imgur.com/4duVe6B.png
